app.controller('aboutMembersCtrl', function($scope) {
	$scope.groupBios = [
	{
		name: "Keerysanth 'Keerush' Sribaskaran", 
		bio: "	Keerysanth is currently a third year computer science student in the software engineering stream at University of Toronto, Scarborough campus. As a computer science student, he has gained extensive experience in object oriented programming and proficient in several programming languages such as Java, Python, Visual Basic, Visual C#, C, HTML and SQL. For 12 months he has worked as a test developer at Caseware International. During his time there, he was developing and analysing tests for the company's web application. As a result, he has gained experience in web automated testing using the Selenium framework, as well as the software development life cycle. He has strong oral communication skills demonstrated through engaging with students as a mentor in the Pathways to Education T.O.P.S program. Also, he has great team working skills developed from working with other members to successfully plan and set up the Scarborough Village annual summer festival.",
		imageLoc: "images/keerush.jpg"
	}, {
		name: "Kent Chow", 
		bio: "	Kent is a third year computer science student at University of Toronto, Scarborough Campus. He has extensive knowledge in programming and is proficient in several programming languages including Java, Python, and C. Kent has a strong passion for learning new software technologies, having experimented with developing Android applications in the past, as well as tinkering with new software libraries while participating in hackathons. Alongside his technical skills learned from school, Kent also has experience working as a test developer. As a result, Kent has a strong foundation in testing software, documenting software bugs, and writing test scripts. Having worked with others in a test development team, Kent also has excellent teamwork and communication skills. Applying his great organization skills, he was able to test and report software patches to development teams before deadlines. In his free time, you can find Kent thinking about the next latest and greatest project to work on, or relaxing by playing video games on his computer.",
		imageLoc: "images/kent.JPG"
	}, {
		name: "Simon Wong", 
		bio: "	Simon is a fifth year student at the University of Toronto, Scarborough Campus. His field of study is in Business Administration with a Specialization in Information Technology. With a large passion for both Business and Computer Science, Simon aspires to be an I.T Project Manager. Simon has completed multiple courses that will prove to be essential for this project including Software Design, System Tools and Systems Programming, Database and Web Applications, Leadership Skills and Communications for Management. Outside of school, Simon has used his knowledge gained from these classes as the Director of Web Communications for the UTSC Management Consulting Club. Some of the duties he performed during his time with this position include managing and updating the club’s website, communicating with the other executives to discuss ideas in improving the website and organizing the club’s online assets. Simon is confident with his passion for computer science and group projects, his contributions will be an invaluable asset to any project.",
		imageLoc: "images/simon.JPG"
	}, {
		name: "Brandon Ramoudith",
		bio: "Brandon is a fourth year computer science student at the University of Toronto Scarborough, specializing in information systems. Brandon has a love for learning, having picked up several programming languages in school, including C, Java and Python. Along with school experience, Brandon has extensive work experience, having worked as a test developer at Caseware as well as a software developer at Index Exchange. During his time at Index, he gained valuable experience using the MEAN stack, as well as learning how to work in an Agile development team, and as a result will be a valuable asset to the team, providing assistance with planning and feature planning. Furthermore, he has great communication skills, constantly being improved during his time as a teaching assistant at the university of Toronto. Finally, during his free time you can find Brandon mentoring new students or streaming on twitch.",
		imageLoc: "images/brandon.jpg"
	}];
});
